[package]
name = "mi-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
uuid ={ version = "*", features = ["serde", "v4"]}
chrono = { version = "*", features = ["serde"]}
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"